[project]
name = "airconvertsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "air[standard]>=0.45.0",
    "ruff>=0.12.8",
    "pygments>=2.19.2",
]
